### PR TITLE
follow best practices regarding tests

### PR DESCRIPTION
**Pull request by tarsius**
- Give the test file a name different from that of the library,
  by appending "-tests" to the feature that is being tested.
- Rename the directory containing the test file to "tests/".
- Add the file ".nosearch" to the directory containing the test
  file.  This prevents `normal-top-level-add-subdirs-to-load-path`
  and similar tools from adding the directory to the `load-path`
  or consider the contained files to be (non-test) libraries.

### CODE REVIEW

**Comment by aaron-em** [comment]
Thanks for the PR! As soon as it's updated so that the Travis build passes, I see no reason not to merge it.

**Comment by tarsius** [comment]
Fixed!

**Comment by tarsius** [comment]
Thanks

**Comment by aaron-em** [comment]
Thanks again for the PR!

**Pull request merged**
